name: PPE Detection App Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 10
    
    steps:
      - name: Launch PPE Detection App
        run: |
          cd /home/sysadmin01/Desktop/PFE/safety
          
          # Set environment for PyTorch
          export TORCH_SERIALIZATION_UNSAFE_GLOBAL_DISABLE=True
          
          # Launch the Flask app with uv
          timeout 30s uv run python -m PPE_Detection.alarm_system.flaskr.main \
            --weights "PPE_Detection/experiments/checkpoints/yolo11n_v6.pt" &
          
          APP_PID=$!
          sleep 5
          
          # Test if app is running
          if ps -p $APP_PID > /dev/null; then
            echo "✓ PPE Detection app started successfully (PID: $APP_PID)"
            
            # Test HTTP endpoint if accessible
            curl -f http://localhost:5000 2>/dev/null && echo "✓ Web interface accessible" || echo "- Web interface check skipped"
            
            # Clean shutdown
            kill $APP_PID 2>/dev/null
            wait $APP_PID 2>/dev/null
            echo "✓ App terminated gracefully"
          else
            echo "✗ Failed to start PPE Detection app"
            exit 1
          fi
