name: PPE Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 10
    
    steps:
    - name: Start PPE App
      run: |
        cd /home/sysadmin01/Desktop/PFE/safety
        source .venv/bin/activate
        nohup uv run python -m PPE_Detection.alarm_system.flaskr.main --weights "/home/sysadmin01/Desktop/PFE/safety/PPE_Detection/experiments/checkpoints/yolo11n_v6.pt" > /tmp/ppe.log 2>&1 &
        echo $! > /tmp/ppe.pid
        sleep 30
        
    - name: Check Status
      run: |
        PID=$(cat /tmp/ppe.pid)
        if kill -0 $PID 2>/dev/null; then
          echo "App is running!"
          ps -p $PID
        else
          echo "App failed to start"
          cat /tmp/ppe.log
        fi
        
    - name: Cleanup
      if: always()
      run: |
        if [ -f /tmp/ppe.pid ]; then
          PID=$(cat /tmp/ppe.pid)
          kill $PID 2>/dev/null || true
          kill -9 $PID 2>/dev/null || true
        fi
        rm -f /tmp/ppe.pid /tmp/ppe.log
